[package]
name = "action_kv"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
crc = "3.2.1"
serde = "1.0.217"
serde_derive = "1.0.217"

[lib]
name = "libactionkv"
path = "src/lib.rs"

[[bin]]
name = "akv_mem"
path = "src/akv_mem.rs"
